// The Fibonacci sequence is the series of numbers 0, 1, 1, 2, 3, 5, 8, ....
// Formally, it can be expressed as:
// fib0 = 0
// fib1 = 1
// fibn = fibn−1 + fibn−2
// Write a multithreaded program that generates the Fibonacci sequence. This
// program should work as follows: On the command line, the user will enter the
// number of Fibonacci numbers that the program is to generate. The program
// will then create a separate thread that will generate the Fibonacci numbers,
// placing the sequence in data that can be shared by the threads (an array is
// probably the most convenient data structure). When the thread finishes
// execution, the parent thread will output the sequence generated by the child
// thread. Because the parent thread cannot begin outputting the Fibonacci
// sequence until the child thread finishes, the parent thread will have to wait for
// the child thread to finish



#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

int *fib_sequence;  // pointer to shared array
int n;              // number of Fibonacci terms

// Thread function to generate Fibonacci numbers
void* generate_fibonacci(void* arg) {
    if (n > 0) fib_sequence[0] = 0;
    if (n > 1) fib_sequence[1] = 1;

    for (int i = 2; i < n; i++) {
        fib_sequence[i] = fib_sequence[i - 1] + fib_sequence[i - 2];
    }

    pthread_exit(0);
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("Usage: %s <number of Fibonacci terms>\n", argv[0]);
        return -1;
    }

    n = atoi(argv[1]);

    if (n <= 0) {
        printf("Please enter a positive integer.\n");
        return -1;
    }

    // Allocate memory for the Fibonacci sequence
    fib_sequence = malloc(n * sizeof(int));
    if (fib_sequence == NULL) {
        perror("malloc failed");
        return -1;
    }

    pthread_t tid;

    // Create thread to compute Fibonacci
    pthread_create(&tid, NULL, generate_fibonacci, NULL);

    // Wait for the thread to finish
    pthread_join(tid, NULL);

    // Print the Fibonacci sequence
    printf("Fibonacci sequence: ");
    for (int i = 0; i < n; i++) {
        printf("%d ", fib_sequence[i]);
    }
    printf("\n");

    // Free memory
    free(fib_sequence);

    return 0;
}
